# Generated by Django 3.2.6 on 2021-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('clothes', 'Clothes'), ('food', 'Food'), ('education', 'Education'), ('household_expense', 'Household Expenses'), ('electronics', 'Electronics')], max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
                'permissions': (('can_view_expenses', 'Grandfather or father can view all family members expenses'),),
            },
        ),
    ]
