# Generated by Django 3.2.6 on 2021-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head of family', 'Head of family'), ('not head of family', 'Not Head of family')], default='not head of family', max_length=255),
        ),
    ]
